const mongoose = require('mongoose');

const { Schema } = mongoose;

const GrantApplicationSchema = new Schema({
  nearId: String,
  firstname: String,
  lastname: String,
  dateOfBirth: Date,
  email: String,
  github: String,
  twitter: String,
  workingAloneOrTeam: String,
  aboutTeam: String,
  teamMembers: Array,
  hasPreviouslyReceivedFundingTokensGrantsFromNear: Boolean,
  aboutTokensReceivedFromNear: String,
  projectName: String,
  grantType: String,
  grantCategory: String,
  projectUrl: String,
  githubUrl: String,
  projectStatus: String,
  projectLaunchDate: Date,
  projectDescription: String,
  currency: String,
  fundingAmount: Number,
  nearFundingAmount: String,
  whatAndWhy: String,
  competitionDifference: String,
  openSourceState: String,
  opensourceComponentUse: String,
  impactOnEcosystem: String,
  excitementNear: String,
  successMesurement: String,
  projectRaisingRound: String,
  attachment: String,
  addressCountry: String,
  addressCity: String,
  addressStreet: String,
  addressZip: String,
  howHeardGrants: String,
  referral: String,
  teamReferral: String,
  comments: String,
  dateLastDraftSaving: Date,
  dateSubmission: Date,
  proposalNearTransactionHash: String,
  isNearProposalValid: Boolean,
  dateEvaluation: Date,
  dateInterviewScheduled: Date,
  dateInterview: Date,
  dateInterviewCompletionConfirmation: Date,
  dateDenial: Date,
  dateApproval: Date,
  dateKycCompletion: Date,
  dateKycDenied: Date,
  dateKycApproved: Date,
  dateAgreementSignature: Date,
  dateOnboardingMeeting: Date,
  dateFirstPaymentSent: Date,
  dateOnboardingCompletion: Date,
  helloSignRequestId: String,
  interviewUrl: String,
  kycUrl: String,
  agreementUrl: String,
  invoiceUrl: String,
  reviewProject: String,
  reviewMemberDetail: String,
  reviewAttachments: String,
  milestones: Array,
  payments: Array,
});

module.exports = mongoose.model('GrantApplication', GrantApplicationSchema);
